### ISSUE TITLE
conductor: remove `GossipNetwork` from `Driver`

### ISSUE THREAD

**Issue by noot** [astriaorg/astria#111]
see discussion here: https://github.com/astriaorg/astria/pull/106#discussion_r1234511611

these may also be relevant: 
- addition of `Exclusive` to sync: https://github.com/rust-lang/rust/pull/97629
- rust internals discussion: https://internals.rust-lang.org/t/what-shall-sync-mean-across-an-await/12020

**Comment by joroshiba** [comment]
With #325 deciding not to implement gossipnet, this is no longer necessary. The new work to connect to sequencer should likely be done outside of Driver.
