### ISSUE TITLE
Consider "borrowing" all of Penumbra's work on testnet deployments

### ISSUE THREAD

**Issue by jbowen93** [astriaorg/astria#113]
main dir: https://github.com/penumbra-zone/penumbra/tree/main/deployments

smoke test: https://github.com/penumbra-zone/penumbra/blob/main/deployments/scripts/smoke-test.sh

testnets: https://github.com/penumbra-zone/penumbra/tree/main/testnets

**Comment by jbowen93** [comment]
File where testnet data is generated 
https://github.com/penumbra-zone/penumbra/blob/main/crates/bin/pd/src/testnet/generate.rs

**Comment by noot** [comment]
closing due to staleness
