### ISSUE TITLE
sequencer: have mempool expose highest nonce stored for account

### ISSUE THREAD

**Issue by Lilyjjo** [astriaorg/astria#1151]
It'd be convenient for users if they could ask the sequencer for the next nonce to use for an account. This would aid composer services if they had to restart with transactions in flight. TODO if the endpoint returns the highest nonce stored or the next nonce to use if a nonce gap is present (maybe both?).

**Comment by noot** [comment]
this already exists in the pending nonce endpoint: https://github.com/astriaorg/astria/blob/main/crates/astria-sequencer/src/grpc/sequencer.rs#L166
