### ISSUE TITLE
`Address::to_raw` sets both inner and bech32m when they are mutually exclusive

### ISSUE THREAD

**Issue by sambukowski** [astriaorg/astria#1180]
`to_raw` fn: https://github.com/astriaorg/astria/blob/c31c10b6db41b19fdce8e4b172363f855d88be23/crates/astria-core/src/primitive/v1/mod.rs#L451

**Comment by SuperFluffy** [comment]
Looking at the function, it sets the field to `Bytes::new()`, which is the correct thing to do. The default value of a unset protobuf `bytes` field is "empty".

Closing this as not-fix because it's correct and the bug report wrong.
