### ISSUE TITLE
update readme to have build instructions

### ISSUE THREAD

**Issue by noot** [astriaorg/astria#132]
- need to add that buf is a depedency
- also just add better instructions in general

**Comment by SuperFluffy** [comment]
I think I would like to generate the rust protobuf types and include them in the repository. This way users only have to install `buf` if they want to regenerate the protobuf code, or if they add things to it. Should make for a better user experience.

**Comment by noot** [comment]
agreed, would be good to update the CI to ensure that the types in the repo match what's generated by buf in that case
