### ISSUE TITLE
Create newtype for transaction hash

### ISSUE THREAD

**Issue by Fraser999** [astriaorg/astria#1353]
We should create a newtype wrapper struct `TransactionHash([u8; 32])`.

This will improve type safety and will allow for implementing `Display` and `Debug` in terms of base64-encoding the bytes, which in turn will reduce some boilerplate elsewhere and ensure consistency in how the hash is displayed.

┆Issue Number: ENG-698

**Comment by ethanoroshiba** [comment]
Close in #1410
