### ISSUE TITLE
sequencer: Containerize rust sequencer, create in CI/CD pipeline

### ISSUE THREAD

**Issue by joroshiba** [astriaorg/astria#139]

**Comment by noot** [comment]
i need this to get the tests working on #137 - should i attempt to do this in that PR, or skip the failing tests and do in a follow-up?

**Comment by joroshiba** [comment]
@noot Let's not skip the failing tests, and get this done as a part of #137

**Comment by joroshiba** [comment]
We can also add a workflow, it should be fairly easy since it's templated, see previous examples [here](https://github.com/astriaorg/astria/blob/main/.github/workflows/docker-build.yml)

**Comment by noot** [comment]
@joroshiba thanks for pointing that out! i'll add the workflow first in a PR, then work on adding the setup to #137
