### ISSUE TITLE
block ordering and tx inclusion action rules

### ISSUE THREAD

**Issue by joroshiba** [astriaorg/astria#1412]
Sudo actions have some interesting side effects to the rest of the block, and as such should be posted at the bottom of the block with no non sudo actions occuring after them. We may even want a hierarchical order in which groupings can occur, and rules about coupling:

I propose the following transaction groupings, all actions in the same groupings have a property of if they can be bundled. If they can, they can only be bundled with same grouping txs. They are in order of how they should appear in a block.

1. General
    - These are general purpose txs which have no odd implications on later txs
    - Bundlable? ✅
    - Can charge fees
    - Actions
      - `TransferAction`
      - `SequenceAction`
      - `BridgeLockAction`
      - `BridgeUnlockAction`
      - `IbcRelay`
      - `Ics20Withdrawal`
      - `ValidatorUpdate`
2. Bridge Control
    - Bundlable? ❌
    - These actions change fundamentals on the signing account. They can't be bundled cleanly because same signer can't do another action after it. Additionally, can have implications on txs in general validity based on ordering. Putting after makes clean break.
    - Charge fees
    - Actions
      - `InitBridgeAccountAction`
      - `BridgeSudoChangeAction`
3. Sudo Actions
    - Bundlable? ✅
    - Most of these have implications on fees charged and valid, affect all txs which have fees and must be after any tx which can charge fees. IbcRelayer affects the validity of `IbcRelay` actions as such should be towards end of block.
    - No fees, submittable only by sudo actor
    - Actions
      - `FeeAssetChangeAction`
      - `FeeChangeAction`
      - `IbcRelayerChangeAction`
4. Sudo Control
    - Bundlable? ❌
    - This updates the sudo account, impossible to have more than one in a valid bundle. The sudo account is also the payee of fees, so it needs to be after all fee paying items, it would affect the validity of any sudo actions. I think it's best to include after any such actions occur.
    - `SudoAddressChangeAction`

I think these might be best viewed as a sort of "action category" where a transaction can only have actions that are all the same category, and categories have two properties (priority, and if it can be bundled). Thus the category of the first action would the that for the whole transaction, and stateless checks can easily be added over this. 

┆Issue Number: ENG-750

**Comment by noot** [comment]
regarding #2 (bridge control):
> These actions change fundamentals on the signing account. They can't be bundled cleanly because same signer can't do another action after it. Additionally, can have implications on txs in general validity based on ordering. Putting after makes clean break.

I don't think these necessarily need to go at the end of the block as they don't affect fees/fee recipient. having implications on validity seems fine, as other actions can also do that (eg transfers)

**Comment by joroshiba** [comment]
> I don't think these necessarily need to go at the end of the block as they don't affect fees/fee recipient. having implications on validity seems fine, as other actions can also do that (eg transfers)

transfers are much easier to account for in mempool design by having a pending balance and will generally not lead to otherwise valid txs being kicked out of the mempool. Want to avoid what could be a demotion from being a kicked out of mempool tx. 

If we already have multiple priority categories it is an improvement to have these after in terms of UX, I don't see a reason to not have as it's own considered type/priority. I think this alone wouldn't necessarily push us to implement these but if doing so we should do it.

**Comment by SuperFluffy** [comment]
I think this issue should be reopened and potentially reverted. While the order of operations has indeed a non-trivial effect on block production, these changes themselves add a lot of complexity on top of block production itself. The implementation itself then adds overhead and makes execution harder to understand.

The bundleable/non-bundleable groups were already addressed by the design and implementation of the execution flow: if an action changed the authorized account, subsequent actions would not be executable. This was an elegant emergent property of the implementation and easy to understand.

This issue and it's iimplementation layers complexity on top of this making the execution flow harder to understand.
