### ISSUE TITLE
Simplify ics20 bridge lock transfer by moving refund check one level up

### ISSUE THREAD

**Issue by SuperFluffy** [astriaorg/astria#1420]
The following argument should be removed and the function only be called if `is_refund` from the higher level logic: https://github.com/astriaorg/astria/blob/acf8c0804e5428b64d407cf5c267e947db8f70e5/crates/astria-sequencer/src/ibc/ics20_transfer.rs#L551

The following argument should be removed and the function only be called if `is_refund` from the higher level logic: https://github.com/astriaorg/astria/blob/acf8c0804e5428b64d407cf5c267e947db8f70e5/crates/astria-sequencer/src/ibc/ics20_transfer.rs#L551

I.e. something like this:
```rust
if !is_refund {
    execute_ics20_transfer_bridge_lock(...)
}
```

┆Issue Number: ENG-756

**Comment by noot** [comment]
i believe this was closed by #1495
