### ISSUE TITLE
Investigate sequencer network upgrade options

### ISSUE THREAD

**Issue by Fraser999** [astriaorg/astria#1423]
We need to get a firmer idea on how to go about upgrading the network, and what options are available to us in terms of `cnidarium` functionality.

┆Issue Number: ENG-759

**Comment by noot** [comment]
cnidarium has a `perform_migration` option on db commits: https://github.com/penumbra-zone/penumbra/blob/772fc69034907cddfca5e68b08ef92b016968d89/crates/cnidarium/src/storage.rs#L360

if `perform_migration` is true, the state at the current version is overwritten (ie version is not incremented on commit like it normally is), essentially giving you the option to migrate state values at some block
