### ISSUE TITLE
Use the correct encoding for `ethers` hashes in the bridge's conversion logic

### ISSUE THREAD

**Issue by itamarreif** [astriaorg/astria#1427]
Essentially, we were using `ethers::H256::to_string()` to get the string for the `rollup_transaction_hash` value, which returns a shortened version of the hash. the string `0x1234...0x1234` is instead of the full hash (i.e. you would expect it to give you something like `0x1234567890123456789012345678901234567890123456789012345678901234`). The fix is to use `encode_hex` instead of `to_string`.

┆Issue Number: ENG-764

**Comment by SuperFluffy** [comment]
Reopening because this is not yet implemented.
