### ISSUE TITLE
refactor and merge logic to spin up isolated k8s test environments

### ISSUE THREAD

**Issue by SuperFluffy** [astriaorg/astria#143]
Right now `astria-conductor-test` and `astria-sequencer-relayer-test` have a lot of code duplication for:

1. k8s yamls (sequencer-relayer has exactly the same environment as conductor, minus geth and sequencer-relayer)
2. rust logic to spin up the test environment by reading the yamls and interacting with the k8s api through kube-rs

In addition, astria-celestia-jsonrpc-client also has a subset of conductor's and sequencer-relayer's k8s deployment.

All of these should be refactor and merged.

**Comment by noot** [comment]
closing as we removed the k8s test environments
