### ISSUE TITLE
sequencer: improve `accounts/state_read_ext.rs` `get_account_balances()` functions with async stream

### ISSUE THREAD

**Issue by Lilyjjo** [astriaorg/astria#1450]
In writing PR #1408, it was not clear how to best return the balances of an account from the underlying database in a way that was useful for both the mempool and the query logic. The mempool needs a map and the query needs a sorted object with the goal of reduced allocations for both.

@SuperFluffy thinks writing an async stream would fix both 

(will add code pointers after PR lands)

┆Issue Number: ENG-788

**Comment by SuperFluffy** [comment]
Closed by https://github.com/astriaorg/astria/pull/1453 into https://github.com/astriaorg/astria/pull/1408
