### ISSUE TITLE
understand celestia rpc commitment construction

### ISSUE THREAD

**Issue by SuperFluffy** [astriaorg/astria#147]
The celestia json rpc client introduced in #135 intentionally left the `commitment` sent to `blob.Get` empty because it is not clear how this commitment is supposed to be constructed.

This issue is to track how this construction has to happen (for example if celestia publishes official docs on this).

**Comment by noot** [comment]
https://github.com/celestiaorg/celestia-app/blob/101390db201a4244a21d393c18fa99b079a98b5c/x/blob/types/payforblob.go#L218

**Comment by joroshiba** [comment]
non-actionable stale ticket, closing
