### ISSUE TITLE
conductor: queue for block ordering and execution

### ISSUE THREAD

**Issue by noot** [astriaorg/astria#15]
we need to execute blocks in order, without any gaps. however, this is not guaranteed by the current implementation.

we should implement some sort of queue that ensures blocks are executed in the correct sequence, and a block cannot be executed without its parent being the current head.

**Comment by emhane** [comment]
https://github.com/astriaorg/astria/issues/332 makes issue obsolete

**Comment by joroshiba** [comment]
secure websocket does not fully solve issue, we need lower level prevention of out of order execution for exceptional cases.

**Comment by noot** [comment]
closing as duplicate/stale of #475 and #471 and #464
