### ISSUE TITLE
Reimplement bridge state reads as streams

### ISSUE THREAD

**Issue by SuperFluffy** [astriaorg/astria#1544]
`astria-sequencer:bridge::state_ext::StateRead` contains several trait methods that perform state reads using a prefix, returning a collection of items. These reads should be replaced by streams and the allocation moved to the caller.

This is to improve performance in an async context and avoid unnecessary allocations.

I recommend to tackle this issue after https://github.com/astriaorg/astria/pull/1525 lands.

Trait methods to be changed:
+ [`StateRead::get_deposit_rollup_ids`](https://github.com/astriaorg/astria/blob/f11f9000a28a4a2959ee488bfad73b751a4194c9/crates/astria-sequencer/src/bridge/state_ext.rs#L288)
+ [`StateRead::get_deposit_events`](https://github.com/astriaorg/astria/blob/f11f9000a28a4a2959ee488bfad73b751a4194c9/crates/astria-sequencer/src/bridge/state_ext.rs#L309)
+ [`StateRead::get_block_deposits`](https://github.com/astriaorg/astria/blob/f11f9000a28a4a2959ee488bfad73b751a4194c9/crates/astria-sequencer/src/bridge/state_ext.rs#L323)

Priori art in the codebase can be found in the accounts component:
+ [`AccountAssetsStream`](https://github.com/astriaorg/astria/blob/f11f9000a28a4a2959ee488bfad73b751a4194c9/crates/astria-sequencer/src/accounts/state_ext.rs#L85)
+ [`AccountAssetBalancesStream`](https://github.com/astriaorg/astria/blob/f11f9000a28a4a2959ee488bfad73b751a4194c9/crates/astria-sequencer/src/accounts/state_ext.rs#L120)

┆Issue Number: ENG-832

**Comment by noot** [comment]
all these methods were actually deleted in #1549, so closing for now
