### ISSUE TITLE
relayer: gossip newly proposed blocks; only write finalized blocks

### ISSUE THREAD

**Issue by noot** [astriaorg/astria#161]
as @joroshiba said:
> relayer should probably gossip the most recently seen block no matter what. So long as its exceedingly rare to receive a bad block, the latency hit would be a full block time for soft confirmations.
> relayer should only ever write to DA data from 1 block below the current max height. This is final final not maybe final.

currently, the relayer gossips and writes to DA newly proposed blocks, however a newly proposed block is not guaranteed to be final. thus, it should only be written once it's final, ie. there is a commit for it.

relates to #50 on the conductor side, but different issues still.

**Comment by emhane** [comment]
cometbft rpc call for latest block returns finalised block from store
2 /3 majority confirmed
https://github.com/astriaorg/cometbft/blob/342404c9011137cb0e9a4abfd9fa1fc2f9ca889e/consensus/state.go#L1626-L1631
then block stored 
https://github.com/astriaorg/cometbft/blob/342404c9011137cb0e9a4abfd9fa1fc2f9ca889e/consensus/state.go#L1700-L1707

as relayer is a sidecar to the sequencer (running cometbft client) receives blocks on localhost, blocks are guaranteed to come in sequential order with respect to block height.
