### ISSUE TITLE
sequencer: make fee change testing easier to debug

### ISSUE THREAD

**Issue by ethanoroshiba** [astriaorg/astria#1715]
As mentioned [here](https://github.com/astriaorg/astria/pull/1701#discussion_r1810756793), this macro will be difficult to debug, so we should replace it.

┆Issue Number: ENG-944

**Comment by SuperFluffy** [comment]
The macro itself will be impossible to debug because the error message will point to a line of code that doesn't exist/only exists after expansion.

The fix is not to fix the macro but to replace it.
