### ISSUE TITLE
sequencer: rename `sourceActionIndex` to `positionInTransaction`

### ISSUE THREAD

**Issue by ethanoroshiba** [astriaorg/astria#1735]
We should rename all instances of `source_action_index` to `position_in_transaction` to be clearer about what this field means.

┆Issue Number: ENG-950

**Comment by SuperFluffy** [comment]
Is this still an open issue? I believe you closed it with #1718?

**Comment by ethanoroshiba** [comment]
> Is this still an open issue? I believe you closed it with #1718?

@SuperFluffy there are many instances of `source_action_index` that I think should still be changed to match, though I realize the issue said `sourceActionIndex` before. I've adjusted the description accordingly.
