### ISSUE TITLE
conductor: rework filtering and logging of data submitted to data availability

### ISSUE THREAD

**Issue by SuperFluffy** [astriaorg/astria#179]
> for later fixing: I wonder if a warn here is too heavy handed? Anyone can submit data to DA namespaces, filtering out the garbage is probably at most worthy of an info? Maybe we have a warn but only at a "received X number of non parseable blobs from DA at height X"? And then have a debug level for each individual one?
>
> Similar below, although we likely want to differentiate between non-parsable and incorrectly signed. Both could be an issue, but also could be just normal noise.

_Originally posted by @joroshiba in https://github.com/astriaorg/astria/pull/150#discussion_r1262721108_

**Comment by noot** [comment]
closing as this doesn't seem relevant as data reading was moved
