### ISSUE TITLE
Fetch not only latest block from sequencer, but also potentially missed blocks

### ISSUE THREAD

**Issue by SuperFluffy** [astriaorg/astria#181]
> this, combined with the `get_latest_block` for polling means blocks can potentially be missed if the polling time isn't fast enough.

_Originally posted by @noot in https://github.com/astriaorg/astria/pull/150#discussion_r1261883414_

**Comment by noot** [comment]
@emhane feel free to open an issue for that solution, I think this issue is no longer needed when #333 is done so closing for now
