### ISSUE TITLE
Separate public sequencer API from sequencer binary crate

### ISSUE THREAD

**Issue by SuperFluffy** [astriaorg/astria#191]
https://github.com/astriaorg/astria/pull/129 introduced the `sequencer-client` crate and made `sequencer` a dependency of it. This caused all crates that use the client to transitively pull in all of sequencer and its dependencies blowing up their compile times (especially due to rocksdb).

The types that are part of sequencer's public API should be split out into their own crate (for example `sequencer-rpc`), and made a dependency of sequencer, sequencer-client, etc.

Sequencer can subsequently be closed down again (making its now public types crate-private again).

**Comment by noot** [comment]
closed by #311
