### ISSUE TITLE
sequencer: use serialization for data that isn't json

### ISSUE THREAD

**Issue by noot** [astriaorg/astria#20]
Currently, we're just using json for serializing data before writing to Celestia. We should probably use something like protobuf at least for now, and eventually look into compression formats.

**Comment by itamarreif** [comment]
issue #12 adds proto definitions to the `astria-proto` crate

still need to do:
- [ ] convert from proto types into the sanitized types we have in the  crate (e.g. conversions from protobuf `bytes` to `Base64String`)
- [ ] replace JSON deserialization with protobuf in `sequencer-relayer`
- [ ] update `conductor` and `sequencer-relayer` to use proto defs
- [ ] get rid of duplicate `tendermint-rs` types (some, e.g. `Header`, were copied over into [`types.rs`](https://github.com/astriaorg/astria/blob/main/crates/astria-sequencer-relayer/src/types.rs)) and use [`tendermint-proto`](https://docs.rs/tendermint-proto/latest/tendermint_proto/) instead

**Comment by itamarreif** [comment]
related documentation tasks:
- [ ] comments explaining what `block_hash` and `block_height` refer to in `SequencerNamespaceData` and `RollupNamespaceData`
    - [ ] in rust code
    - [ ] in proto definitions
- [ ] comments explaining what `block_index` refers to in `IndexedTransaction` and what it's used for
    - [ ] in rust code
    - [ ] in proto definitions
- [ ] relationship between namespace data objects and the block object
    - [ ] comments on the rust types
    - [ ] comments on the proto definitions
    - [ ] hopefully a data flow diagram for the sequencer-relayer

**Comment by noot** [comment]
blocked by #258

**Comment by noot** [comment]
closed by #395
