### ISSUE TITLE
use tendermint.rs conversion methods for headers

### ISSUE THREAD

**Issue by SuperFluffy** [astriaorg/astria#21]
I noticed that we are converting to tendermint headers ourselves. We should rely on their upstream impls to save some work: https://docs.rs/tendermint/0.30.0/tendermint/block/header/struct.Header.html#impl-TryFrom%3CHeader%3E-for-Header:

https://github.com/astriaorg/sequencer-relayer/blob/442a1723a61ab0aec5e44626a1bb8c74b12f76f3/src/types.rs#L125-L126

**Comment by xeno097** [comment]
Hi, I'd like to take this on. Any suggestions would be highly appreciated. A doubt that I have is if the currently used `Header` type should be completely replaced by the `tendermint::Header` because they seem to have the same fields but some types differ.

**Comment by noot** [comment]
@xeno097 hey, thank you for the interest! I think @itamarreif might be working on this already, can you confirm?

**Comment by xeno097** [comment]
Oh ok, thank you for letting me know that!
