### ISSUE TITLE
Construct celestia client with an explicit reqwest client

### ISSUE THREAD

**Issue by SuperFluffy** [astriaorg/astria#22]
At the moment `CelestiaClient` is constructed with an implicitly created `reqwest::Client` (through rs-cnc). It's best practice to create one `reqwest::Client` and `clone` it because `Client` is just a thin wrapper around a `Arc` to a connection pool.

https://github.com/astriaorg/astria/blob/afd0fbe1fd1a0419c1e93596e6c5bfa74ccc6a94/crates/astria-sequencer-relayer/src/da.rs#L165

**Comment by haythemsellami** [comment]
Would love to give a short at this. The fix PR should be in https://github.com/astriaorg/sequencer-relayer right?
