### ISSUE TITLE
conductor: reevaluate block queue parent/executed block relations after new v1alpha2 api is implemented

### ISSUE THREAD

**Issue by sambukowski** [astriaorg/astria#220]
investigate how the block queue looks at block relationships once #205 has been implemented
specifically look at `Executor::last_executed_seq_block_hash`

**Comment by sambukowski** [comment]
the current implementation of the block queue in #284 does keep this in mind. so the refactor here is likely to be limited.

**Comment by joroshiba** [comment]
Duplicate of #285 + #230
