### ISSUE TITLE
sequencer: implement `check_tx` error codes

### ISSUE THREAD

**Issue by noot** [astriaorg/astria#228]
`check_tx` currently returns 0 for ok and 1 for error. tendermint defines any nonzero value as error. we can return different error codes depending on the error. these don't strictly need to match cosmos but might be nice if they do.

**Comment by ShivangRawat30** [comment]
Hey I am currently learning rust, as it is a good first issue can you please assign this to me.

**Comment by noot** [comment]
done by #311
