### ISSUE TITLE
conductor: either execute all blocks or offer setting - add `execute_commit_level` setting

### ISSUE THREAD

**Issue by joroshiba** [astriaorg/astria#230]
Currently Conductor only executes blocks which have transactions. This is an opinionated take on what constitutes a block to the rollup, rollups can have empty blocks. We should either allow the rollup to make that decision when `execute_block` is called or offer configuration for conductor which allows this behavior to be changed.

**Comment by sambukowski** [comment]
related to: #205 #207

**Comment by sambukowski** [comment]
Closing this as #250 and #285 cover the same scope.
