### ISSUE TITLE
conductor: better logging on bad data ingestion

### ISSUE THREAD

**Issue by joroshiba** [astriaorg/astria#231]
We filter out data which is not valid when read from DA for conductor, but we should have some better logging, ie information about:

- Data blocks which fail to be serialized into proper format
  - Should be able to use the logs to manually fetch & test data
- Information about data from DA which is parsed but invalid
  - Want to be able to manually check

**Comment by sambukowski** [comment]
Related to #313

**Comment by SuperFluffy** [comment]
All of this was addressed in the refactor https://github.com/astriaorg/astria/pull/946

[`FetchConvertAndVerify::execute`](https://github.com/astriaorg/astria/blob/5387149274df37a382a21ccf0e431c73deee0c42/crates/astria-conductor/src/celestia/mod.rs#L499) (permalink to current main) is instrumented with a Celestia height and the sequencer/rollup namespaces. All steps involved in reconstructing a sequencer/rollup block now emit the relevant errors under that instrumented span (fetch, decompression, decoding and validation of invariants, verification against sequencer, matching of sequencer metadata to rollup data)
