### ISSUE TITLE
composer: gracefully shut down provider connections

### ISSUE THREAD

**Issue by dereksione** [astriaorg/astria#233]
## Motivation

The composer refactor made it such that each provider added to the collector gets assigned its own async task where is has an incoming connection to a node client and it forwards the transactions it receives through this subscription connection to the collector. However, since these async tasks are interfacing with the outside world, it is important to be able to gracefully shut down these connections instead of abruptly dropping them. These graceful shutdown procedures may differ from provider implementation to provider implementation, but it is important that they are called when appropriate when the collector does decide that a shutdown of the connection is the best course of action (perhaps due to unexpected behavior - see #232).

## Subtasks

- [ ] Ensure that for all the Provider types that implement the composer provider interface, there is a graceful shutdown implementation
- [ ] Smoke test graceful shutdowns for the above Provider implementations

**Comment by SuperFluffy** [comment]
Let's only create follow-up issues for PRs that are about to be submitted.

**Comment by itamarreif** [comment]
this is stale - updated version at #341
