### ISSUE TITLE
astria-rs-cnc integration tests need celestia running

### ISSUE THREAD

**Issue by SuperFluffy** [astriaorg/astria#25]
The roundtrip test in `astria-rs-cnc` needs a `celestia` node listening on port `26659` and will fail otherwise.

Locally the error is not clear (might need a better message), but on CI we need to provide it with a test environment similar to what is done in `astria-conductor` and `astria-sequencer-relayer`.

**Comment by noot** [comment]
closing b/c rs-cnc was deleted
