### ISSUE TITLE
composer: collector config should support multiple rollups

### ISSUE THREAD

**Issue by itamarreif** [astriaorg/astria#276]
In order to support reading transactions from multiple rollups (#214), the config needs to be changed to parse `chain_id, rpc` tuples for multiple rollups.

A `Rollup` config struct should be added to encompass this tuple and a vector of the tuples should be read from an environment variable as a string and parsed as a regex.

The environment variable should be specified in the format `foo::ws://example.one,bar::https://example.two`

1. Chain ID for the rollup
2. `::` separator between `chain_id` and `rpc`
3. RPC URL for rollup node
4. comma separator between tuples

**Comment by itamarreif** [comment]
this is addressed by #277, #278, #282

**Comment by SuperFluffy** [comment]
Closed by #277
