### ISSUE TITLE
Separate k8s test environment deployments into pods

### ISSUE THREAD

**Issue by SuperFluffy** [astriaorg/astria#28]
Because our test environment pods started their life on podman all containers were made part of a single pod. Now that we are running on kubernetes it makes more sense to split the containers out into separate pods, connect them via services, and stop worrying about overlapping ports. This should simplify a lot of test setups by using defaults.

As raised in a peer review:

> 2/3 of these arguments are default values. `--sequencer-endpoint=http://localhost:1318` is the only one that is not a default because we're manually configuring Metro for `1318`, but I think that was changed from `1317` to avoid port conflicts, which are no longer a concern.
> 
> Could we start Metro on `1317` again, which would allow us to get rid of all three of these arguments?
> 
> _Originally posted by @steezeburger in https://github.com/astriaorg/astria/pull/6#discussion_r1199144867_

**Comment by noot** [comment]
I think #150 closes this

**Comment by SuperFluffy** [comment]
With #150 merged the only crate remaining is `astria-celestia-jsonrpc-client` that needs a k8s deployment of celestia to run tests (which will be kept to run integration tests against an actual RPC server).

#187 will remove k8s/kind from CI for most tests.
