### ISSUE TITLE
conductor: empty block execution setting

### ISSUE THREAD

**Issue by sambukowski** [astriaorg/astria#285]
Currently the Conductor does nothing when it receives empty blocks.
More specifically, the `executor::Executor::execute_block()` returns `None` when it receives an empty block and never makes a call to `DoBlock`.

Is this the long term desired functionality?

Depending on the use case, having an option to either ignore or execute empty blocks may be useful.

**Comment by sambukowski** [comment]
Putting a reference to this here: https://github.com/astriaorg/astria/blob/9725475d197f9e0dea072fc840a97a76fbf0d59b/crates/astria-conductor/src/executor/mod.rs#L211

**Comment by noot** [comment]
yeah `do_block` can handle an empty block fine, just have to call with with no txs. we can have a setting for it if regular block times are preferred

**Comment by sambukowski** [comment]
pr in the works #373
