### ISSUE TITLE
submit entire shared sequencer block to celestia in single transaction

### ISSUE THREAD

**Issue by itamarreif** [astriaorg/astria#30]
Currently we submit a separate PFB (pay-for-bytes) transaction to Celestia for each rollup's transactions rather than a single transaction for the entire shared sequencer block.
The reason for this is that Celestia does not yet support batching data to multiple namespaces in a single transaction. However, this is likely to change in the near future as there is an existing PR to change this.
- [code for submit](https://github.com/celestiaorg/celestia-app/blob/c121c285005c0b5d47542fd955fc5be688905e1a/x/blob/payforblob.go#L17-L54)
- [code for commitment](https://github.com/celestiaorg/celestia-app/blob/c121c285005c0b5d47542fd955fc5be688905e1a/x/blob/types/payforblob.go#L168-L235)

This means a cross-rollup bundle wouldn't be atomic because there would be one Celestia tx for rollup A and one for rollup B. This has several implications/problems:
1. A shared sequencer block can be partially censored by a Celestia node.
2. A shared sequencer block can be spread over several Celestia nodes due to gas limits.
This affects the liveness guarantees that the shared sequencer provides to the rollups built on it and with it potentially the MEV market. Generally, the current situation is not desirable and needs to be updated once the changes are incorporated into Celestia.

When making this change, issue #31 should also be addressed.

**Comment by noot** [comment]
blocked on #11 / https://github.com/astriaorg/dev-cluster/issues/38 (need to update to JSON-RPC using rc5)
