### ISSUE TITLE
refactor data published over gossipnet 

### ISSUE THREAD

**Issue by noot** [astriaorg/astria#309]
Currently, the data published over gossipnet is a `SequencerBlockData`, which is published over one topic, which conductor subscribes to.

There are two problems with this:
1. conductor does no validation of the received `SequencerBlockData` rollup data (it can't, since it's missing inclusion proofs right now)
2. conductor receives data for every rollup, even though it doesn't need to. it should only receive rollup data for its own rollup, along with block data needed for verification.

Gossip and the data published should be updated as follows:
1. there should be a topic for sequencer block headers which sequencer block headers + last commits are published on (as one structure), all conductors will subscribe to this
2. conductor should subscribe to the topic designated by its chain ID
3. relayer should publish rollup data to the topic designated by its chain ID
4. the rollup data published should be updated to include the merkle inclusion proof of itself inside the block's action tree root (for verification, the same way data is verified when read from DA right now) and conductor should verify this

A problem with this design is if rollup data is published on some topic, and the conductor somehow misses this data, there is no request-response protocol for it to fetch this data if it sees it's missing it. However this is ok as it can later get this data from DA. or if we want to implement a request-response protocol later, we can.

**Comment by noot** [comment]
blocked by decision on #325

**Comment by joroshiba** [comment]
We are going to remove the gossipnet, which removes need to refactor data published over it.
