### ISSUE TITLE
flatten `SequencerBlock` protos

### ISSUE THREAD

**Issue by itamarreif** [astriaorg/astria#31]
# Current situation
The current `SequencerBlock` proto definition has a nested array of transactions:
```protobuf
// data.proto
// IndexedTransaction represents a sequencer transaction along with the index
// it was originally in the sequencer block.
message IndexedTransaction {
    uint64 block_index = 1; // TODO: this is usize - how to define for variable size?
    bytes transaction = 2;
}

// block.proto
message NamespacedIndexedTransactions {
    bytes namespace = 1;
    repeated IndexedTransaction txs = 2;
}

// SequencerBlock
message SequencerBlock {
    bytes block_hash = 1;
    tendermint.types.Header header = 2;
    repeated IndexedTransaction sequencer_transactions = 3;
    repeated NamespacedIndexedTransactions rollup_txs = 4;
}
```

# The problem
The problem with this, as described by Janis:
"From my experience deeply nested repeated types (so fields with a `repeated` prefix and things like `map`) are tricky from a performance-standpoint, because rust (or any language) can't amortize memory allocation away.So if you have soomething like `Vec<Vec<T>>` and lots of small inner vectors (say with 20 elements on average), you will end up with 4 memory allocations per inner vector (4 -> 8 -> 16 -> 32). Let's say you have 100 elements in the outer vector, that's 406 memory allocations in total, 400 memory allocations for the inner vecs + 6 allocations for the outer vec (`4 -> 8 -> 16 -> 32 -> 64 -> 128`).If you find a way to flatten this data structure so that you just have a 1d vector with 400 elements in total, you can bring this down from 406 to 8 (`128 -> 256 -> 512`)."

# Proposed solutions
As discussed, there are several possible solutions to this:
1. Flatten the `namespace` into each `IndexedTransaction`, i.e. have:
    ```protobuf
    // block.proto
    message NamespacedIndexedTransaction {
        bytes namespace = 1;
        IndexedTransaction tx = 2;
    }
    
    // SequencerBlock
    message SequencerBlock {
        bytes block_hash = 1;
        tendermint.types.Header header = 2;
        repeated IndexedTransaction sequencer_transactions = 3;
        repeated NamespacedIndexedTransaction rollup_txs = 4;
    }
    ```
    where `SequencerBlock.rollup_txs` is the flattened vector of all the rollup txs.
    This has the effect of adding a `namespace` for each transaction, instead of one per rollup. The result is a potentially significantly increased block size for the sequencer-relayer to gossip along with soft commitments.
2. Store all `IndexedTransaction`s in one long vector, and add a vector of `(namespace, length)` tuples that can be used to break apart the long vector into rollup-specific vectors of `IndexedTransaction`s:
    ```protobuf
    // block.proto
    message RollupTxLength {
        bytes namespace = 1;
        uint64 length = 2;
    }
    
    message SequencerBlock {
        bytes block_hash = 1;
        tendermint.types.Header header = 2;
        repeated IndexedTransaction sequencer_transactions = 3;
        repeated IndexedTransaction rollup_txs = 4;
        repeated RollupTxLength rollup_lengths = 5;
    }
    ```
    This makes the serialized blocks less resource intensive by avoiding the repeated `namespace`s added in the previous approach and the nested vector reallocations as described by Janis above.
    However, it comes at the cost of added complexity in implementation and requiring heavy documentation for future maintenance. More specifically, any implementation would have to add logic along the lines of:
    ```rust
    pub struct SequencerBlock {
        pub block_hash: Base64String,
        pub header: Header,
        pub sequencer_txs: Vec<IndexedTransaction>,
        pub rollup_txs: HashMap<Namespace, Vec<IndexedTransaction>>,
    }

    impl From<SequencerBlockProto> for SequencerBlock {
        fn from (value: SequencerBlockProto) -> Self {
            // init empty sequencer block
            let block: SequencerBlock = SequencerBlock::default();
            // convert from bytes to Base64String and so on
            // ...
            // parse rollup txs
            value.rollup_lengths
                .iter()
                .map(|(namespace, len)| 
                    block.rollup_txs[namespace] = value.rollup_txs.iter()
                        .take(len)
                        .collect::<Vector<IndexedTransaction>>();
                )
            }
    }
    ```

# Context
I chose to leave this issue for later implementation because the definition of `SequencerBlock` is likely to change in the near future.
Specifically, the current structure is a result of the fact that we are submitting each rollup's transactions to Celestia in a separate PFB (pay-for-bytes) transactions. This is because Celestia does not support batching data to multiple namespaces in a single transaction.
However, this is likely to change in the near future as there is an existing PR to change this.
- [code for submit](https://github.com/celestiaorg/celestia-app/blob/c121c285005c0b5d47542fd955fc5be688905e1a/x/blob/payforblob.go#L17-L54)
- [code for commitment](https://github.com/celestiaorg/celestia-app/blob/c121c285005c0b5d47542fd955fc5be688905e1a/x/blob/types/payforblob.go#L168-L235)
I propose that this issue be resolved when we address this change.
Issue #30 was created to address this issue.

**Comment by noot** [comment]
closed by #395
