### ISSUE TITLE
Verifying signed transactions is not reliable because protobuf serialization is not deterministic

### ISSUE THREAD

**Issue by SuperFluffy** [astriaorg/astria#310]
The protobuf `SignedTransaction` message needs to be changed to contain the raw byte stream encoding an unsigned transaction so that the signature and verification key can be applied to the raw bytes:
```protobuf
// Proposal
message SignedTransactionNew {
  bytes signature = 1;
  bytes verification_key = 2;
  bytes transaction = 3;
}
// Current
message SignedTransactionOld {
  bytes signature = 1;
  byte verification_key = 2;
  UnsignedTransaction transaction = 3;
}
```
The problem with the current scheme is that when a signed transaction is received over the wire and decoded into a rust native `SignedTransaction`, the raw bytes that made up the inner `UnsignedTransaction` are lost and there is no way to get them back. This is because protobuf serialization is not deterministic, and can change between languages and even version of the parser library. See https://gist.github.com/kchristidis/39c8b310fd9da43d515c4394c3cd9510.

Currently, in order to guarantee that the signed transaction indeed matches the signature and verification key, we have a flow like this:
```
signed tx bytes
-> unverified SignedTransactionOld
-> encode inner unsigned transaction to unsigned tx bytes (!!)
-> apply verification key and signature to unsigned tx bytes (??)
-> verified SignedTransaction
```
The problem is the encoding step marked with `(!!)`: there is no guarantee that the bytes of that step match the bytes of the original transaction that was send over the wire, and hence that this passes the verification check marked with `(??)`. Currently we don't encounter issues because all signed tx construction happens in services that are all locked to the same version of `prost`, and so they do produce the same byte-output.

With the proposed `SignedTransactionNew` the flow would be changed:
```
signed tx bytes
-> unverified SignedTransactionNew
-> apply verification key and signature to inner tx bytes
-> decode inner tx bytes to `UnsignedTransaction`
-> verified SignedTransaction
```

**Comment by noot** [comment]
proposed solution:

update `SignedTransaction` to contain a `google.protobuf.Any` instead of an `UnsignedTransaction`:

```
message SignedTransaction {
  bytes signature = 1;
  bytes public_key = 2;
  google.protobuf.Any transaction = 3;
}
```

then, the signature can be verified over the bytes in the `Any` instead of an `UnsignedTransaction` which needs to be reserialized.

**Comment by SuperFluffy** [comment]
Agree, that's the right way of moving forward.
