### ISSUE TITLE
Intern chain IDs when constructing a sequencer block data from tendermint

### ISSUE THREAD

**Issue by SuperFluffy** [astriaorg/astria#318]
When iterating over the data in a tendermint block there are likely many more actions than chain IDs and hence namespaces constructed from the chain IDs. To avoid rehashing the same chain ID on every iteration the namespace should be stored in a map (from chain ID to namespace).

**Comment by joroshiba** [comment]
> To avoid rehashing the same chain ID on every iteration the namespace should be stored in a map (from chain ID to namespace).

I think we want to explicitly avoid state growth by new chains. It probably makes sense to have a cache for this in the relayer. I don't think this is a major performance concern though. It is likely the kind of optimization which makes sense but isn't strictly necessary.

**Comment by noot** [comment]
this can be closed as `Namespace` was removed from `SequencerBlockData` in #346
