### ISSUE TITLE
conductor: reader - block sorting and continuity checks when read from DA

### ISSUE THREAD

**Issue by sambukowski** [astriaorg/astria#323]
When blocks are read from DA the reader eventually sort all the blocks here: https://github.com/astriaorg/astria/blob/bffd952e3bed90009f35ec947fd673c8bfa190f2/crates/astria-conductor/src/reader.rs#L256

Checks need to be added to make sure that blocks are in order and there are no missing blocks.

**Comment by sambukowski** [comment]
Sequencer blocks from DA are sorted here: https://github.com/astriaorg/astria/blob/954ac8b117240f7790ab6a2a3b11cd3e41b1b493/crates/astria-conductor/src/data_availability.rs#L434

But still missing checks to make sure these are continuous.

**Comment by noot** [comment]
closing as duplicate of #464
