### ISSUE TITLE
sequencer: return error responses for consensus service

### ISSUE THREAD

**Issue by itamarreif** [astriaorg/astria#370]
The consensus service currently does not return any errors for the consensus ABCI methods (`begin_block`, `deliver_tx`, etc.)

In combination with #369, error responses should be added so that services interacting with the sequencer, as well as other sequencer nodes, are able to handle interactions that currently fail silently.

While implementing #364, @SuperFluffy and I looked into how error handling is currently done and have determined that the `ActionHandler` abstraction likely need to be reworked for errors to be handled properly. There are several issues:

1. `ActionHandler` is currently implement both for `UnsignedTransaction` as well as for `Actions` such as `TransferAction` and `SequencerAction`. `UnsignedTransaction` has no stateless checks required, just a stateful check for nonce validity. It also not executed, and the `execute()` implementation for it simply calls `execute()` on each of the actions it contains. The trait shouldn't be implemented for this type 
2. Signature validation, a stateless check on the `SignedTransaction` should clarify that this is a stateless check that failed.

Summarizing the types of checks for each type involved:

`SignedTransaction`
- only a stateless check, signature validation

`UnsignedTransaction`
- only a stateful check, nonce validation

Actions, such as `SequenceAction` or `TransferAction`
- stateless check (e.g. source of transfer must have signed the transaction)
- stateful check (e.g. sufficient funds)
- execution & related error handling

Clarification following comments: I mean returning responses with error codes, not `Error` results from the ABCI functions.

**Comment by SuperFluffy** [comment]
@noot I think the wording in this issue is not optimal. What I think the OP is getting at is that the sequencer services that respond to requests forwarded from cometbft should respond with non-zero codes.

So I'm reading "error" as "abci response with code > 0". We should amend the issue and related PRs to make the distinction clear.

**Comment by noot** [comment]
closing for now as `check_tx` now returns appropriate error codes - other ABCI functions don't return error codes.
