### ISSUE TITLE
Change use of 'finalized' in conductor to 'available' or 'executed'

### ISSUE THREAD

**Issue by emhane** [astriaorg/astria#396]
rn conductor refers to executed blocks as final, imo this causes a lot of confusion with cometbft finality. conductor will receive final blocks from the shared-sequencer. as opposed to specifying 'final with respect to execution' or similar, 'available' evidently describes a block received seen on the data availability layer and 'executed' evidently describes a block that successfully executed.

**Comment by jbowen93** [comment]
I believe we chose to use the same wording as Optimism Bedrock https://community.optimism.io/docs/developers/bedrock/differences/#chain-reorganizations

**Comment by emhane** [comment]
alright maybe the solution is to incorporate the use of `safe` blocks in the codebase, rn it isn't. for example, what finality does this "final sequencer block" refer to in this rust doc? and which is the L1, DA or execution layer or both?

https://github.com/astriaorg/astria/blob/f21e30ddaf692fd7f4fc225b767d9c7b4ce0ee62/crates/astria-conductor/src/executor.rs#L112-L118
