### ISSUE TITLE
conductor: update spec to reflect removal of gossipnet

### ISSUE THREAD

**Issue by SuperFluffy** [astriaorg/astria#404]
PR #383 missed removal of `gossip` in some doc comments.

**Comment by noot** [comment]
should be done as part of  #334 perhaps?

**Comment by SuperFluffy** [comment]
We also have the conductor spec to update, which is so detailed it goes into implementation details. Updating the title of this issue to reflect that.

All mentions of gossip are removed in #407 from astria-conductor.
