### ISSUE TITLE
sequencer: investigate how abci request can be handled with free-standing handlers

### ISSUE THREAD

**Issue by SuperFluffy** [astriaorg/astria#408]
It's unfortunate that the test for the thing you want to test is so far away from it.

If we define request handlers as freestanding functions rather than inherent methods on types we can test the handles independently and inject the necessary state as needed.

That's how axum is designed

_Originally posted by @SuperFluffy in https://github.com/astriaorg/astria/pull/364#discussion_r1326963183_

**Comment by noot** [comment]
closing as the query fns are now free-standing
