### ISSUE TITLE
composer: address backpressure issue resulting from transaction submission.

### ISSUE THREAD

**Issue by itamarreif** [astriaorg/astria#409]
The `Searcher` object currently suffers from backpressure resulting from transaction submission to the sequencer:

1. `Executor` can't send (awaits indefinitely)
1. `Searcher` sends to `Executor` until its channel is full, then it blocks on the `send.await`
1. `Collector`s send to `Searcher` until that channel is full, then they all block on `send.await` (to the searcher)

The realistic fix for this is to move out the bundling logic into a separate `Bundler` actor and manage this like a buffer in there:

1. Transactions would get collected by `Collector`s and fed into the `Bundler` via a channel by the `Searcher`.
1. The `Bundler` serializes and packs in to a buffer, i.e. the `Vec<Action>` payload of a Sequencer transaction, and occasionally flushes the buffer by forwarding the bundle to the `Executor` for submission.

Backpressure would be explicitly managed and parameterized in the `Bundler` actor. A max transaction size (in bytes) would need to be determined for the `Bundler` to manage the size of the buffer, and the `Bundler` would have to make sure that a sequencer transaction is forwarded to the `Executor` either:

1.  When the buffer is full, or
1. Once every sequencer block

**Comment by itamarreif** [comment]
A quicker patch for this would be to use `send_timeout()` which would fail when backpressure accumulates. Logging this would give us insight to how critical this fix is.

**Comment by itamarreif** [comment]
#599 is also somewhat related

**Comment by joroshiba** [comment]
Multiple improvments have built here and we have load tested without backpressure issues.
