### ISSUE TITLE
Change Chain IDs to be String

### ISSUE THREAD

**Issue by SuperFluffy** [astriaorg/astria#433]
yeah I prefer `String` since I think it should be human-readable, but `SequenceAction::chain_id` is a `Vec<u8>` and since this is user-supplied it may not be a utf8 string. we should probably change that type to `String` also, if you agree I can open an issue

_Originally posted by @noot in https://github.com/astriaorg/astria/pull/346#discussion_r1323835526_

**Comment by noot** [comment]
closing as we changed chain IDs to be 32-bytes
