### ISSUE TITLE
conductor: sync full node from sequencer/celestia

### ISSUE THREAD

**Issue by joroshiba** [astriaorg/astria#439]
Conductor works right now only on a new rollup node, new transactions come in and can be executed. We want to update the architecture such that on startup, it will sync from a configured starting block for sequencer + DA  to sync from history before starting to follow the head block.

**User Journey**
User deploys a rollup locally during development, generates data which is pushed to live sequencer network + celestia network. Data is preserved by these networks, and they want to be able to start a cloud hosted node. They deploy their rollup on their cloud provider, tell it where to start syncing from and get all their local test/starting block data by syncing.

**Comment by sambukowski** [comment]
I stated a design doc in Notion for planning the implementation of this:
https://www.notion.so/astria-org/Conductor-Sync-Design-09f56f2b2ab04a0c8a5d13e83e279719
