### ISSUE TITLE
conductor: ensure that sequencer blocks are strictly in order and contiguous

### ISSUE THREAD

**Issue by SuperFluffy** [astriaorg/astria#465]
sync on startup: Yes, that is correct.

previous version: Looking at current `main`, I don't think we had that, at least not for the sequencer part.

trigger sync via command: I think we can leave this squarely inside the `sequencer::Reader` actor so that executor need not be concerned with it: we can add logic to the sequencer reader to track the current height and require it be contiguous. If we detect a hole, we can explicitly fetch that block and pause forwarding to the executor until the hole is plugged.

Follow-up PR?

_Originally posted by @SuperFluffy in https://github.com/astriaorg/astria/pull/455#discussion_r1345574419_

**Comment by sambukowski** [comment]
This pr: https://github.com/astriaorg/astria/pull/553, added some checks to make sure that blocks cannot get executed out of order

**Comment by sambukowski** [comment]
Upon closer inspection, this function here: https://github.com/astriaorg/astria/blob/a1a7a59c112b7a72b78b6d3efd9c77b77802436c/crates/astria-conductor/src/sequencer/mod.rs#L330
adds a "live" resync when pulling block from the sequencer. If a block is every missed, this function is called and the missing block fetched.

With the order checks added in #553 and the change already added. All blocks pulled from the sequencer and then passed on to the Executor can only be executed in order, and the resync makes sure there are no missing blocks.
