### ISSUE TITLE
Transaction Hashes

### ISSUE THREAD

**Issue by itamarreif** [astriaorg/astria#476]
There's currently no agreed upon way to hash our `SignedTransaction`s (i.e. no method or trait implemented). This is useful for logging as transactions need to be tracked across services.

- [ ] look at how `CometBFT` implements transaction hashing
- [ ] add the functionality to the `SignedTransaction` type

**Comment by noot** [comment]
we should just serialize (ie. proto `encode_to_vec`) then sha256 hash of that

**Comment by SuperFluffy** [comment]
We should not only have an agreed upon way to report the tx hashes of `SignedTransaction`, but also of the bundle within (i.e. the `transactions` hash contained). The reason is that when composer is submitting transactions to sequencer, `SignedTransaction` is not stable since it will change with the included nonce.

**Comment by itamarreif** [comment]
> We should not only have an agreed upon way to report the tx hashes of `SignedTransaction`, but also of the bundle within (i.e. the `transactions` hash contained). The reason is that when composer is submitting transactions to sequencer, `SignedTransaction` is not stable since it will change with the included nonce.

The hash of the rollup's transaction (or whatever else they submit, e.g. a block or a bundle) is determined by the rollup developers. Rather than enforcing a specific hash on the rollup tx (in this case an `ethers::Transaction`, we should just require it to be hashable (is that a word?).

**Comment by noot** [comment]
@itamarreif this issue is pertaining to sequencer tx hashes, which are sha256 due to cometbft
