### ISSUE TITLE
conductor: simulate bad websocket connections

### ISSUE THREAD

**Issue by SuperFluffy** [astriaorg/astria#482]

**Comment by jbowen93** [comment]
This is a good indicator of something where testing in isolation is difficult or impossible and "soak testing" is the best way to validate if a change fixes something. I've run enough different instances of rollups now to say that the conductor crashes and fails to reconnect with high likelihood in <8 hours. 

Would be good to put together a playbook for how to standup a rollup using a WIP change against the remote devnet to perform this kind of soak test.

**Comment by SuperFluffy** [comment]
All websockets were removed fro Conductor.
