### ISSUE TITLE
understand how the gas and fee mechanism of the celestia node works

### ISSUE THREAD

**Issue by SuperFluffy** [astriaorg/astria#510]
Celestia's `blob.Submit` API has the `SubmitOptions` parameter with fields `Fee` and `GasLimit`: https://node-rpc-docs.celestia.org/?version=v0.11.0#blob.Submit

It is not completely clear how they work. What happens if they are omitted? Does celestia-node select one for us? This needs investigation.

**Comment by joroshiba** [comment]
We have migrated to direct celestia app submission,
