### ISSUE TITLE
conductor reader validates `SequencerNamespaceData` before checking that block contains relevant namespace txs

### ISSUE THREAD

**Issue by noot** [astriaorg/astria#54]
as title says, this is because the `Reader` doesn't contain the namespace the conductor cares about, but the `Executor` does, and checks whether the block should be executed. this should be changed so we aren't validating irrelevant blocks.

note: this may not be relevant, and depends upon our design/relation of the conductor to a tendermint light client; if we run a light client internally to the conductor (ie. track the validator set) then we need to keep this, but if we assume we have a trusted external client as we do right now, we can change this.

**Comment by sambukowski** [comment]
This enables execution of empty blocks. Keeping this.
