### ISSUE TITLE
conductor: reevaluate initial da and sequencer heights as config inputs?

### ISSUE THREAD

**Issue by sambukowski** [astriaorg/astria#562]
From @noot's comment in pr https://github.com/astriaorg/astria/pull/553/:

> I find having the `initial_sequencer_block_height` as a config option bad, as it's not something that should be changeable from run to run, it's something that should be a part of the rollup's genesis. imo it's more extensible for rollup developers if this is stored on the execution node (alternatively, the sequencer block hash corresponding to the rollup block hash is stored). this involves updating the API, which i think we should consider.

**Comment by noot** [comment]
closing at these were moved as part of rollup genesis
