### ISSUE TITLE
Apply pedantic clippy checks to the entire repository

### ISSUE THREAD

**Issue by SuperFluffy** [astriaorg/astria#569]
At the moment all crates in the repository are checked with `clippy -- -W pedantic` except for `astria-conductor` and `astria-sequencer-relayer`. We want all crates to pass pedantic checks.

```[tasklist]
### Tasks
- [ ] https://github.com/astriaorg/astria/issues/570
- [ ] https://github.com/astriaorg/astria/issues/571
```

**Comment by noot** [comment]
closing as both tasks are done
