### ISSUE TITLE
Add `celestia` command(s) to `astria-cli`

### ISSUE THREAD

**Issue by jbowen93** [astriaorg/astria#605]
It would be helpful to have commands in the `astria-cli` to read data from Celestia which was posted by the sequencer relayer and to deserialize it into sequencer structs 

Mocha Namespaces we're currently posting to
- https://mocha-4.celenium.io/namespace/000000000000000000000000000000000000be779a4ba5f61c9f6898
- https://mocha-4.celenium.io/namespace/000000000000000000000000000000000000000067480c4a88c4d129
- https://mocha-4.celenium.io/namespace/000000000000000000000000000000000000cb5f0a3b5a3632a1a457

Relevant code for how we posting blobs
- https://github.com/astriaorg/astria/blob/main/crates/astria-celestia-client/src/blob_space.rs
- https://github.com/astriaorg/astria/blob/main/crates/astria-celestia-client/src/client.rs#L162
- https://github.com/astriaorg/astria/blob/main/crates/astria-sequencer-types/src/sequencer_block_data.rs#L173

**Note: The following PRs will change the sequencer data structs**
- https://github.com/astriaorg/astria/pull/395
- https://github.com/astriaorg/astria/pull/436

**Comment by noot** [comment]
closed by #1059
