### ISSUE TITLE
Use single Dockerfile for Conductor & Relayer

### ISSUE THREAD

**Issue by steezeburger** [astriaorg/astria#61]
Conductor and Relayer use an almost identical Dockerfile. 

Let's merge them and use something like `ARG TARGET_BINARY` w/ 
* `TARGET_BINARY=astria-sequencer-relayer`
* `TARGET_BINARY=astria-conductor`

Considerations:
* in what directory does this new, shared Dockerfile go?

**Comment by noot** [comment]
closed by #149
