### ISSUE TITLE
astria-cli error when install cli 

### ISSUE THREAD

**Issue by mangozila** [astriaorg/astria#636]
when running
```rust
git clone git@github.com:astriaorg/astria.git
cd astria
just install-cli
``` 
I met this error 
```
error: Package `astria-test-utils v0.1.0 (/root/astria/crates/astria-test-utils)` does not have feature `tokio`. It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table, so it does not have an implicit feature with that name.
error: Recipe `install-cli` failed on line 43 with exit code 101

```

**Comment by joroshiba** [comment]
I was able to recreate this error but only by running an older version of rust can you try the following command to install?

```
cargo clean
cargo +1.74 install --path ./crates/astria-cli --locked
```

**Comment by mangozila** [comment]
> I was able to recreate this error but only by running an older version of rust can you try the following command to install?
> 
> ```
> cargo clean
> cargo +1.74 install --path ./crates/astria-cli --locked
> ```

right, it seems that there was a error when I installed rust . After reinstalled rust then it fixed. and you right, the problem will be recreated with old version of rust. thanks a lot
