### ISSUE TITLE
sequencer: basic PoA implementation

### ISSUE THREAD

**Issue by noot** [astriaorg/astria#68]
the sequencer node should have a basic PoA `component` type that is able to rotate the validator set. note that cometbft already has the ability to have any amount of validators at genesis, so this component would deal with changing the validator set.

open question:
- when/how do we change the validator set? is it a multisig of the existing validators, or is there a "sudo" key that is allowed to authorize validator set changes?
- do we change the validator set at the next block (or some other defined block height) once a change has been proposed and accepted? or do we implement an epoch-based system where all changes happen at a fixed height?

**Comment by noot** [comment]
can be implemented by setting validator changes here: https://github.com/tendermint/tendermint/blob/v0.34.x/spec/abci/abci.md#endblock

**Comment by noot** [comment]
should also decide how to deal with byzantine validators: https://github.com/tendermint/tendermint/blob/v0.34.x/spec/abci/abci.md#beginblock (just kick them out for now?)

**Comment by noot** [comment]
Proposed design:

We have a sudo key (set in the genesis file) which is authorized to make validator set changes. This can easily be extended later to a multisig set at genesis, then later a dynamic multisig.

A new transaction type is added:
```rust
struct ValidatorUpdate {
     public_key: VerificationKey,
     voting_power: u64, // set to 0 to remove validator
}
```

This matches the `validator::Update` type in tendermint-rs. This tx must be signed by the authorized key and submitted to the sequencer. When this tx is included in a block, `end_block` will return this as a validator change.

We should also update the sequencer application to track the validator set, so that we can ensure that the validator inside the `ValidatorUpdate` is actually in the set if they're being removed.

**Comment by joroshiba** [comment]
> should also decide how to deal with byzantine validators: https://github.com/tendermint/tendermint/blob/v0.34.x/spec/abci/abci.md#beginblock (just kick them out for now?)

Should this be a seperate issue or do we need to deal with right now. Easiest is to just kick them out for now probably, so let's do that, with a massive TODO of potentially problematic.

**Comment by joroshiba** [comment]
@noot Proposed design sounds good to me.

**Comment by noot** [comment]
> Should this be a seperate issue or do we need to deal with right now. Easiest is to just kick them out for now probably, so let's do that, with a massive TODO of potentially problematic. 

yep that's a separate issue, will make another. just wanted to note it here so I don't forget
