### ISSUE TITLE
core: replace allocating display impl

### ISSUE THREAD

**Issue by SuperFluffy** [astriaorg/astria#702]
PR #690 introduced a `Display` impl that allocates:
https://github.com/astriaorg/astria/blob/dc449e7dc89deabd794c134bf5e28bf86d759877/crates/astria-core/src/sequencer/v1alpha1/asset.rs#L106

It should be replaced by an implementation that doesn't alloocate:
https://github.com/astriaorg/astria/blob/dc449e7dc89deabd794c134bf5e28bf86d759877/crates/astria-core/src/sequencer/v1alpha1/mod.rs#L102

**Comment by noot** [comment]
@SuperFluffy  this displays the assets differently, eg:
```
[00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00]
``` 

vs 

`0000000000000000000000000000000000000000000000000000000000000000`

I purposefully want to display the second via `hex::encode`, is there a non-allocating way to do this? if not I'd like to leave it as is.

**Comment by SuperFluffy** [comment]
@noot That does not seem right:
```rust
impl std::fmt::Display for Address {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        for byte in self.0 {
            write!(f, "{byte:02x}")?;
        }
        Ok(())
    }
}

struct Address([u8; 20]);

fn main() {
    let address = Address([42u8; 32]);
    
    println!("the address {address}");
}

// the address 2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a
```
