### ISSUE TITLE
Does Astria sequencer support zk rollups?

### ISSUE THREAD

**Issue by gokulsan** [astriaorg/astria#723]
As I understand from the documentations, Astria is a shared and decentralized sequencer system with cross rollup composability feature support and atomic cross rollup arbitrage possibilities. Is it only restricted to optimism based rollups?

**Comment by jbowen93** [comment]
Whether a rollup uses validity proofs (zk) or fraud proofs (optimistic) for bridging is independent of the sequencer. Rollups built using Astria’s shared sequencer are free to use whatever bridging mechanism they prefer.
