### ISSUE TITLE
Restart executor and readers if execution API rollup returns error

### ISSUE THREAD

**Issue by SuperFluffy** [astriaorg/astria#758]
Conductor should restart its executor and reader tasks if communication with executor fails. Specifically, we should add retry logic for:

1. getting genesis info and initial commitment state;
1. executing blocks and updating state.

However, we must distinguish between network (and other) failures and conductor trying to execute invalid state against the rollup. One idea is to have the rollup return error codes that result in an immediate retart of the executor and reader tasks within conductor.

**Comment by ethanoroshiba** [comment]
Closed with #1463
