### ISSUE TITLE
sequencer/relayer: write deposit info to rollup blobs

### ISSUE THREAD

**Issue by noot** [astriaorg/astria#774]
follow up to #768 - `Deposit`s need to be written to DA for usage by the conductor, this can be implemented by including them in the `SequencerBlock` structure returned by the sequencer API.

**Comment by joroshiba** [comment]
Want to note that we should probably remove `SequencerBlock::try_from_cometbft` from `astria_core` after this is done since it will build an inaccurate `SequencerBlock` without access to sequencer state.

This likely means merging of this is blocked by #789 and #790
