### ISSUE TITLE
Geth startup config relies on access to local storage of Metro

### ISSUE THREAD

**Issue by jbowen93** [astriaorg/astria#78]
TODO: @joroshiba to fill in more details here

**Comment by joroshiba** [comment]
Currently Geth is sharing the keyring volume from Metro. It seems this may not be strictly necessary though. With current configuration Geth requires A volume at /root/.metro but it doesn't need to be the same. I believe we can create a new volume for geth when split into seperate pods.

**Comment by jbowen93** [comment]
What is the required contents of the `.metro` dir for Geth? I'm assuming it needs access to the "god tier" private key which controls all the tokens in metro?

**Comment by joroshiba** [comment]
Geth needs to be able to create new keyrings. I don't believe there is any reason they need to be shared, it used to share the god tier private key. I don't believe that is necessary any longer, because we made txs to metro free.

**Comment by noot** [comment]
I think this can be closed with the retro integration and https://github.com/astriaorg/go-ethereum/pull/24
