### ISSUE TITLE
Define Rollup interface to Shared Sequencer

### ISSUE THREAD

**Issue by jbowen93** [astriaorg/astria#84]
What does it mean when a rollup is "deployed" to the shared sequencer? What components need to get stood up? 

![user-journeys](https://github.com/astriaorg/astria/assets/5825193/9c9d62aa-ff1d-4780-81ed-1ee5a78b2573)

```[tasklist]
### Tasks
```

**Comment by joroshiba** [comment]
The long term vs short term can be different here, on the question of "how does composer get tokens" we can hack around this by making it free until solved.

**Comment by jbowen93** [comment]
I've removed that task as this isn't the right issue to discuss it in. Also removing the `demo` tag. 

I'd like to use this issue as a place to answer questions along the lines of "I am a rollup that would like to use the shared sequencer, what must I do to integrate?" 

The answer to this question needs to be thoroughly documented with diagrams and specific code links.

**Comment by itamarreif** [comment]
See the [`composer` Notion master doc](https://www.notion.so/astria-org/Composer-037492cb2da04f7990abdbc9c2f2f68f?pvs=4).
