### ISSUE TITLE
composer: Move check for sequence action size to collectors

### ISSUE THREAD

**Issue by bharath-123** [astriaorg/astria#892]
Currently in composer. When a sequence action is sent from Collector to the Executor. It is added to a bundle. Before adding to the bundle, we check if the sequence action is larger than the max size permitted in a bundle which is set by https://github.com/astriaorg/astria/blob/main/crates/astria-composer/local.env.example#L48 . If a sequence action is larger than the max size permitted in a bundle, the sequence action is dropped in the executor. This is bad UX as we don't have any way to communicate back to the user that their tx is dropped currently because it is too large. 

We could probably just move the sequence action size check in collectors which can reject the rollup tx before even sending it to the Executor.

**Comment by joroshiba** [comment]
This issue was closed because it was stale
