### ISSUE TITLE
sequencer: ensure duplicate txs passed via `prepare_proposal` are not executed more than once

### ISSUE THREAD

**Issue by noot** [astriaorg/astria#895]
the sequencer does not check that the tx list in `prepare_proposal` does not contain duplicates, this will cause consensus errors as one might execute and the next will fail during the proposal but will succeed for all other nodes as the duplicate will be removed. flagged by zellic. we should remove any duplicates during `prepare_proposal`

**Comment by Lilyjjo** [comment]
With code changes made for 0.38x and full syncs, duplicate transactions are no longer an issue. In PR #992 we removed recording the results of failed transactions, so duplicate transaction will no longer have the effect of causing consensus failures.
