### ISSUE TITLE
relayer: switch to using celestia-app for blob writing

### ISSUE THREAD

**Issue by joroshiba** [astriaorg/astria#921]
## Background
We have had numerous issues submitting blobs through celestia node, related to sequences and timeouts. While the celestia node is aiming to improve this blob submission is key to the functioning or relayer and an unreliable dependency shouldn't be blocking us.

## Solution
Update sequencer relayer to submit blobs directly to celestia-app (the cosmos sdk app of celestia). This will require that we manage our celestia keys locally. We can use [cosmrs](https://docs.rs/cosmrs/latest/cosmrs/tx/index.html) to sign transactions which are generated in protobuf form from celestias `MsgPayForBlobs` [proto](https://github.com/celestiaorg/celestia-app/blob/main/proto/celestia/blob/v1/tx.proto#L17) type. Transactions can be broadcast via grpc to celestia app ([cosmos docs](https://docs.cosmos.network/main/user/run-node/txs#using-grpc)). They should be submitted as `BROADCAST_SYNC` and the txhash can then be used to do a poll using `GetTx` on the grpc client for tx submission.

Prior art of submission is written in go in celestia app: https://github.com/celestiaorg/celestia-app/blob/fd3c6dcb5b6c1386838b09ef886fab54054cb384/pkg/user/signer.go#L162

**Comment by SuperFluffy** [comment]
Maybe useful for constructing correct namespaces, shares, and other types:
We currently submit to celestia-node using [blob.Submit](https://docs.rs/celestia-rpc/latest/celestia_rpc/trait.BlobClient.html#method.blob_submit). This the [`Blob` type](https://docs.rs/celestia-types/0.1.1/celestia_types/blob/struct.Blob.html) with commitment and namespace.
