### ISSUE TITLE
don't show opentelemetry error log when running binaries locally

### ISSUE THREAD

**Issue by noot** [astriaorg/astria#970]
when running the binaries locally, the logs get polluted with the error message:
```
OpenTelemetry trace error occurred. Exporter otlp encountered the following error(s): the grpc server returns error (The service is currently unavailable): , detailed error message: error trying to connect: tcp connect error: Connection refused (os error 61)
```

this is annoying, we should have a config option to disable connecting to opentelemetry entirely or something to silence this error.

**Comment by SuperFluffy** [comment]
This option already exists and is documented for all services. E.g. `ASTRIA_SEQUENCER_NO_OTEL=true` and similarly for the others.
